export const defaultShortcuts: Array<[string | RegExp, any]> = [
    ["container", "relative z-10 flex flex-col w-full mx-auto p-3.5 gap-3.5 text-slate-800"],
    ["flex-center", "flex justify-center items-center"],
    ["col-center", "flex flex-col justify-center items-center"],
    ["flex-between", "flex items-center justify-between"],
    ["flex-items-center", "flex items-center"],
    ["text-ellipsis", "whitespace-nowrap overflow-hidden text-ellipsis"],
    ["abs-center", "absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2"],
    ["btn", "relative inline-flex items-center justify-center px-4 text-sm text-center whitespace-nowrap border border-transparent rounded outline-none"],
    ["btn-primary", "text-white bg-primary border-primary"],
    ["btn-success", "text-white bg-success border-success"],
    ["btn-warning", "text-white bg-warning border-warning"],
    ["btn-danger", "text-white bg-danger border-danger"],
    ["btn-info", "text-white bg-info border-info"],
    ["btn-default", "text-gray-700 bg-white border-gray-300"],
    ["btn-plain", "bg-transparent"],
    ["btn-round", "rounded-full"],
    ["btn-block", "flex w-full"],
    ["btn-disabled", "opacity-50"],
    ["btn-loading", "inline-block w-3.5 h-3.5 mr-1.5 border-2 border-current border-l-transparent rounded-full"],
    ["tag-primary", "px-2 py-1 text-xs text-primary bg-primary-50 rounded"],
    ["action-card", "bg-white rounded-2xl p-4 border border-slate-100"],
    ["u-border-b-dashed", "border-0 border-b-1rpx border-b-dashed border-slate-200"],
    ["u-border-t-dashed", "border-0 border-t-1rpx border-t-dashed border-slate-200"],
    ["u-border-b", "border-0 border-b-1rpx border-b-solid border-slate-200"],
    ["u-border-t", "border-0 border-t-1rpx border-t-solid border-slate-200"],
    ["safe-bottom", "pb-[env(safe-area-inset-bottom)]"],
    [/^w-h-([^-]+)-([^-]+)$/, ([, w, h]: string[]) => `w-${w} h-${h}`],
];
