import fs from 'fs'
import path from 'path'
import { loadEnv as viteLoadEnv } from 'vite'

/**
 * 转换下划线变量名为小驼峰
 */
export function toCamel(key: string): string {
	return key
		.toLowerCase()
		.replace(/^vite_/, '')
		.replace(/_([a-z0-9])/g, (_, letter) => letter.toUpperCase())
}

/**
 * 转换版本字符串为数值代码
 */
export function toCode(version: string): number {
	const [major, minor, patch] = version.split('.').map(Number)
	return major * 10000 + minor * 100 + patch
}

/**
 * 加载当前模式的环境变量
 */
export function loadEnv(mode: string, root: string): Record<string, string> {
	return viteLoadEnv(mode, root, 'VITE_')
}

/**
 * 生成环境配置类型声明代码
 */
export function genDts(envDict: Record<string, string>): string {
	const envLines = Object.entries(envDict)
		.map(([key, value]) => {
			const displayVal = value.includes('\n') ? value.split('\n')[0] + '...' : value
			return `\t\t/** 原始配置值 \`${displayVal}\` */\n\t\t${key}: string`
		})
		.join('\n')

	const camelLines = Object.entries(envDict)
		.map(([key, value]) => {
			const displayVal = value.includes('\n') ? value.split('\n')[0] + '...' : value
			return `\t\t/** 对应 \`${key}\` (配置值 \`${displayVal}\`) */\n\t\t${toCamel(key)}: string`
		})
		.join('\n')

	return `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by @hlw-uni-mp/vite-plugin. Do not edit directly.

declare global {
	const __APP_NAME__: string
	const __APP_VERSION_CODE__: number
	const __APP_VERSION_NAME__: string
	const __APP_BASE_URL__: string
	const __APP_WSS_URL__: string
	const __APPID__: string

	interface HostEnvMap {
${envLines}
		[key: string]: unknown
	}

	interface HostEnvCamelMap {
${camelLines}
		[key: string]: unknown
	}

	type HostEnv = HostEnvMap & HostEnvCamelMap
	type HostEnvKey = keyof HostEnvMap | keyof HostEnvCamelMap | string

	interface ImportMetaEnv {
${envLines}
		[key: string]: any
	}

	interface ImportMeta {
		readonly env: ImportMetaEnv
	}
}

export type { HostEnvMap, HostEnvCamelMap, HostEnv, HostEnvKey }
`
}

/**
 * 写入环境类型声明文件
 */
export function writeDts(targetFile: string, content: string): void {
	fs.mkdirSync(path.dirname(targetFile), { recursive: true })
	if (fs.existsSync(targetFile) && fs.readFileSync(targetFile, 'utf-8') === content) return
	fs.writeFileSync(targetFile, content, 'utf-8')
}
